### ISSUE TITLE
电脑端默认开启搜索输入栏需要怎么改

### ISSUE THREAD

**Issue by lliuz** [Dreamer-Paul/Single#15]
Paul, 非常感谢你的制作的主题，很好看，我有一个小想法但从没接触过前端，我想在电脑端默认打开搜索栏的输入框，手机端保持默认不打开，能否提供些建议。
![image.png](http://images.lliuz.top:63080/images/2018/12/26/image.png)

**Comment by Dreamer-Paul** [comment]
添加一段自己的 CSS 就可以，我想的一个办法是直接适配屏幕宽度的，你只需要贴进去就行，这样也不影响以后的主题更新。

```css
@media screen and (min-width: 599px){
    .head-search{
        opacity: 1;
        pointer-events: inherit;
    }
}
```
